In [1]:
import pandas as pd

/root/.venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)

### Считаем файл в датафрейм

In [2]:
df = pd.read_csv('../data/feed-views.log',
                 sep='\t',
                 skiprows=[2, 3],
                 skipfooter=2,
                 names = ['datetime', 'user'],
                 index_col='datetime',
                 engine='python')

In [3]:
df.head()

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [4]:
df.tail()

                                 user
datetime
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

### Переименуем datetime в date_time

In [5]:
df.index.name = 'date_time'

### Сохраним в формате csv, в качестве разделителя воспользуемся ';'

In [8]:
df.to_csv('../data/feed-views-semicolon.log', sep=';')