In [4]:
import pandas as pd

### Создадим датафрейм со столбцами datetime и user, с последующим добавлением столбцов year, month и т.д.

In [5]:
df = pd.read_csv('../data/feed-views.log', 
                 sep='\t', 
                 names = ['datetime', 'user'], 
                 engine='python')
df['datetime'] = pd.to_datetime(df['datetime'])
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second'] = df['datetime'].dt.second

In [6]:
df.head()

                    datetime   user  year  month  day  hour  minute  second
0 2020-04-17 12:01:08.463179  artem  2020      4   17    12       1       8
1 2020-04-17 12:01:23.743946  artem  2020      4   17    12       1      23
2 2020-04-17 12:27:30.646665  artem  2020      4   17    12      27      30
3 2020-04-17 12:35:44.884757  artem  2020      4   17    12      35      44
4 2020-04-17 12:35:52.735016  artem  2020      4   17    12      35      52

### Создадим столбец daytime и установим столбец user индексом

In [7]:
df['daytime'] = pd.cut(df['hour'],
                       bins=[0, 4, 7, 11, 17, 20, 24],
                       labels=['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening'],
                       right=False)
df.set_index('user', inplace=True)

In [8]:
df.head()

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon

### Посчитаем кол-во элементов в датафрейме

In [9]:
df.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [10]:
df['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

### Отсортируем значения по столбцам hour, minute, second в порядке возрастания

In [11]:
df.sort_values(['hour','minute', 'second'])

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

### Рассчитаем различные минимумы и максимумы

In [12]:
night_df = df[df['daytime'] == 'night']
max_hour_night = night_df['hour'].max()
print(max_hour_night)

3

In [13]:
morning_df = df[df['daytime'] == 'morning']
min_hour_morning = morning_df['hour'].min()
print(min_hour_morning)

8

In [14]:
df[df['hour'] == max_hour_night]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,night

In [15]:
df[df['hour'] == min_hour_morning]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning

In [16]:
df['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

### Выведем 3 самых ранних часа и 3 самых поздних часа в категории morning

In [17]:
morning_df.nsmallest(3, 'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning
artem,2020-04-24 09:42:47.598208,2020,4,24,9,42,47,morning

In [18]:
morning_df.nlargest(3, 'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 10:53:52.623447,2020,4,18,10,53,52,morning
maxim,2020-04-18 10:56:55.833899,2020,4,18,10,56,55,morning
konstantin,2020-04-18 10:57:37.331258,2020,4,18,10,57,37,morning

### Соберем базовую статистику по столбцам

In [19]:
describe = df.describe()
describe

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [20]:
iqr = describe['hour']['75%'] - describe['hour']['25%']
print(iqr)

9.0